name: api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10.2
    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust
      run: |
        apt install -y curl gcc
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Setup Elixir
      run: |
        mix local.hex --force
        mix local.rebar --force
    - name: Build and setup
      run: |
        . $HOME/.cargo/env
        RUSTFLAGS="-C target-feature=-crt-static" MIX_ENV=test mix do deps.get, compile --warnings-as-errors
    - name: Exec tests
      run: MIX_ENV=test mix test
